import ThemeProviderClient from "./ThemeProviderClient";
import { DM_Serif_Display, Bai_Jamjuree } from "next/font/google";
import "./globals.css";

const dmSerifDisplay = DM_Serif_Display({
  subsets: ["latin"],
  variable: "--font-dmSerif",
  weight: "400",
});

const baiJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  variable: "--font-baiJamjuree",
  weight: "400",
});

export const metadata = {
  title: "Medicova",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dmSerifDisplay.variable} ${baiJamjuree.variable}`}>
        <ThemeProviderClient>{children}</ThemeProviderClient>
      </body>
    </html>
  );
}
